import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import { Suspense } from "react";
import Loading from "./loading";
import "./globals.css";
import Subscriber from "./components/subscriber";
import TopProgressBar from "./components/top-progress-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TopProgressBar />
        <Suspense fallback={<Loading />}>
          <Navbar />
          {children}
          <Footer />
          <Subscriber />
        </Suspense>
      </body>
    </html>
  );
}
